version: '3.9'

services:
  web:
    build:
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
